### ISSUE TITLE
Is image patching supported with BIGIP 15.x OVAs?

### ISSUE THREAD

**Issue by drennalls** [f5devcentral/tmos-cloudinit#4]
I attempted to use the [f5devcentral/tmos-image-patcher image on DockerHub](https://hub.docker.com/r/f5devcentral/tmos-image-patcher) to generate a patched version of the BIGIP-15.1.2.1-0.0.10.ALL-vmware.ova to try out the [tmos_static_mgmt module](https://github.com/f5devcentral/tmos-cloudinit#the-tmos_static_mgmt-cloudinit-module). The patching seemed to work ok, however the static ip defined was not configured.

From trying to debug things on the VM that was deployed I noticed that although I see the [cc_tmos_static_mgmt.py](https://github.com/f5devcentral/tmos-cloudinit/blob/master/image_patch_files/system_python_path/site-packages/cloudinit/config/cc_tmos_static_mgmt.py) module (and others that were injected) under `/usr/lib/python-2.7/site-packages/cloudinit/config`, it was not listed in cloud-init's `cloud.cfg` i.e. it's disabled. Is image patching supported on BIGIP 15.x OVAs?

**Comment by jgruberf5** [comment]
OVAs work, as evidenced by the injection of the modules, but you have to have a cloudinit data source to read in your user_data containing the static IP information. The default patching uses OpenStack configdrive data sources. Did you create a configdrive ISO disk with the OpenStack file layout and attach it to your VE before booting?

There is a container tool to help you do that included with the repo:

https://github.com/f5devcentral/tmos-cloudinit#creating-openstack-formatted-cloudinit-configdrive-isos
https://github.com/f5devcentral/tmos-cloudinit/tree/master/tmos_configdrive_builder

What was in your use_data YAML file found at /openstack/latest/user_data on the generated and attached configdrive ISO?

It must at least have this:

`#cloud-config
tmos_static_mgmt:
  enabled: true
  ip: xxx.xxx.xxx.xxx
  netmask: xxx.xxx.xxx.xxx
  gw: xxx.xxx.xxx.xxx
  mtu: xxxx`

What does /var/log/cloudinit.log show?
What does /var/log/f5-cloudinit.log show?

**Comment by drennalls** [comment]
I was using a configdrive iso produced using the [f5devcentral/tmos-configdrive-builder image on DockerHub](https://hub.docker.com/r/f5devcentral/tmos-configdrive-builder). The .iso was attached to the VM before booting :smile: 

> What was in your use_data YAML file found at /openstack/latest/user_data on the generated and attached configdrive ISO?

My `user_data` looked like this..
```
#cloud-config
tmos_static_mgmt:
  enabled: true
  ip: xxx.xxx.xxx.xxx
  netmask: xxx.xxx.xxx.xxx
  gw: xxx.xxx.xxx.xxx
  mtu: xxxx
  icontrollx_trusted_sources: false
  icontrollx_package_urls:
    - https://github.com/F5Networks/f5-declarative-onboarding/releases/download/v1.19.0/f5-declarative-onboarding-1.19.0-2.noarch.rpm
    - https://github.com/F5Networks/f5-appsvcs-extension/releases/download/v3.19.1/f5-appsvcs-3.19.1-1.noarch.rpm
  post_onboard_enabled: true
  post_onboard_commands:
    - tmsh modify sys db ui.advisory.color { value orange }
    - tmsh modify sys db ui.advisory.text { value  'Onboarded with OpenStack Metadata' }
    - tmsh modify sys db ui.advisory.enabled { value true }
    - tmsh modify sys db provision.extramb { value 500 }
    - tmsh modify sys global-settings gui-setup disabled
    - tmsh modify sys provision ltm level minimum
    - tmsh modify sys provision asm level minimum
chpasswd:
  list: |
    root: ...etc..
    admin:...etc..
  expire: False

ssh_authorized_keys:
  - ssh-rsa ...etc.
```

> What does /var/log/cloudinit.log show?

The VM has since been deleted as I'd moved on to trying to use the ovf properties for static config instead. I'll have to reproduce and grab the full of logs. However, I could tell from the log file which modules had been executed. I saw tmos_declared mentioned and that's what led me to check the cloud.cfg file where I saw no mention of  cc_tmos_static_mgmt.

On that note, I'm thinking perhaps my issue might be due to using the [f5devcentral/tmos-image-patcher:latest@sha256:df0145c23b36ba216a644fed1051314d8ccf80d501d26441ae51b27c02cab170 image on DockerHub](https://hub.docker.com/layers/f5devcentral/tmos-image-patcher/latest/images/sha256-df0145c23b36ba216a644fed1051314d8ccf80d501d26441ae51b27c02cab170?context=explore) which seems to be older/out-of-date and seems to be pre-cloud-config templating? 
```
$ docker run --entrypoint bash -ti --rm f5devcentral/tmos-image-patcher:latest@sha256:df0145c23b36ba216a644fed1051314d8ccf80d501d26441ae51b27c02cab170 -c "grep -A3 'def patch_images' ./tmos-cloudinit/tmos_image_patcher/tmos_image_p
atcher.py"
def patch_images(tmos_image_dir, tmos_cloudinit_dir,
                 tmos_usr_inject_dir, tmos_var_inject_dir,
                 tmos_config_inject_dir, tmos_shared_inject_dir,
                 tmos_icontrollx_dir):
```
..`patch_images` has `cloud_template_file` param (like the [current version does](cloud_template_file)) and the image has no `TMOS_CLOUDINIT_CONFIG_TEMPLATE` env var, and I'm guessing that's why the cloud.cfg I saw had no mention of any of the injected modules.

> What does /var/log/f5-cloudinit.log show?

It was empty.
